# Generated by Django 5.2 on 2025-05-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('point_of_contact', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.CharField(blank=True, choices=[('rack', 'Rack'), ('barrel', 'Barrel'), ('reel_to_reel', 'Reel to Reel'), ('roll_to_roll', 'Roll to Roll'), ('other', 'Other')], max_length=20)),
                ('process', models.CharField(max_length=200)),
                ('substrate', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlaterBuilder.customers')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['project_id'],
            },
        ),
    ]
