# Generated by Django 5.2 on 2025-05-12 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaterBuilder', '0002_projects_sketch_projects_spec_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.CharField(max_length=10)),
                ('process_step', models.IntegerField()),
                ('process', models.CharField(max_length=200)),
                ('dwell_time', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_map_entries', to='PlaterBuilder.projects')),
            ],
            options={
                'verbose_name_plural': 'Process Map Entries',
                'ordering': ['process_step'],
            },
        ),
    ]
