# Generated by Django 5.2 on 2026-02-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaterBuilder', '0004_processmapentry_productiongoal_simulationparameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiongoal',
            name='target_parts_per_shift',
            field=models.FloatField(blank=True, help_text='Target parts per shift', null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='recipe_results',
            field=models.JSONField(blank=True, help_text='Per-recipe throughput breakdown', null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='station_utilization',
            field=models.JSONField(blank=True, help_text='Per-station utilization data', null=True),
        ),
        migrations.AlterField(
            model_name='productiongoal',
            name='primary_target',
            field=models.CharField(choices=[('hour', 'Parts Per Hour'), ('shift', 'Parts Per Shift'), ('day', 'Parts Per Day'), ('week', 'Parts Per Week'), ('month', 'Parts Per Month'), ('year', 'Parts Per Year')], default='day', help_text='Primary production target timeframe', max_length=20),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('production_ratio', models.IntegerField(default=1, help_text='Weight in the production mix (e.g. 3 in a 3:2:1 split)')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='PlaterBuilder.projects')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.CharField(max_length=10)),
                ('process_name', models.CharField(help_text='What happens at this station', max_length=200)),
                ('position_index', models.IntegerField(help_text='Physical sort order on the line')),
                ('tank_length', models.FloatField(default=0.0, help_text='Tank length in meters')),
                ('tank_width', models.FloatField(default=0.0, help_text='Tank width in meters')),
                ('distance_to_next', models.FloatField(default=0.0, help_text='Distance to next station in meters')),
                ('is_loading_station', models.BooleanField(default=False)),
                ('is_unloading_station', models.BooleanField(default=False)),
                ('requires_manual_handling', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='PlaterBuilder.projects')),
            ],
            options={
                'verbose_name_plural': 'Stations',
                'ordering': ['position_index'],
                'unique_together': {('project', 'station_number')},
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(help_text='Order of this step within the recipe')),
                ('dwell_time', models.IntegerField(blank=True, help_text='Standard dwell time in seconds', null=True)),
                ('min_dwell_time', models.IntegerField(blank=True, help_text='Minimum dwell time in seconds', null=True)),
                ('max_dwell_time', models.IntegerField(blank=True, help_text='Maximum dwell time in seconds', null=True)),
                ('drip_time', models.IntegerField(default=0, help_text='Drip time after lifting in seconds')),
                ('notes', models.TextField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='PlaterBuilder.recipe')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_steps', to='PlaterBuilder.station')),
            ],
            options={
                'verbose_name_plural': 'Recipe Steps',
                'ordering': ['step_order'],
                'unique_together': {('recipe', 'step_order')},
            },
        ),
        migrations.DeleteModel(
            name='ProcessMapEntry',
        ),
    ]
